# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    ens33:
      addresses: 
        - 192.168.0.251/24
      nameservers:
        search: [dns.google.com, cdns1.cox.net]
        addresses: [8.8.8.8, 68.105.28.11]
      routes:
        - to: default
          via: 192.168.0.1

# sudo nano /etc/netplan/00-installer-config.yaml
# sudo netplan apply
